### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by ElenaNya** [MaxBogomol/WizardsReborn#18]
[crash-2024-06-08_13.46.18-fml.txt](https://github.com/user-attachments/files/15748263/crash-2024-06-08_13.46.18-fml.txt)

client logs in, but server crashes, I realize that this is alpha, especially which is not yet on either modrinth or curseforge, but wanted to let you know.

wizards_reborn-1.20.1-0.1.3.jar (downloaded yesterday)

**Comment by MaxBogomol** [comment]
I committed fixes related to rendering of GUI particles
you can make a build

**Comment by ElenaNya** [comment]
Thanks!!
