### ISSUE TITLE
JEI + Wizards Reborn

### ISSUE THREAD

**Issue by ElenaNya** [MaxBogomol/WizardsReborn#19]
When open a page with Wizards Reborn in JEI, the whole JEI fills with ERROR symbol, if you use EMI it just crashes.

jei-1.20.1-forge-15.3.0.4.jar
wizards_reborn-1.20.1-0.1.3.jar (from yesterday)
![image](https://github.com/MaxBogomol/WizardsReborn/assets/94359925/3b4d8476-243d-4eb2-a001-a1370394c700)

**Comment by MaxBogomol** [comment]
Братан, я абсолютно не знаю что у тебя не так с джеи, вероятно с этим связаны какие-то другие моды.
Ты даже крашлогов и тд не оставил. Возможно стоит перейти в дискорд сервера и там обсудить это.

**Comment by ElenaNya** [comment]
> Братан, я абсолютно не знаю что у тебя не так с джеи, вероятно с этим связаны какие-то другие моды. Ты даже крашлогов и тд не оставил. Возможно стоит перейти в дискорд мода и там обсудить это.

Не подумал сразу логи дать, думал известная проблема, в целом нужно просто установить эти два мода вместе (разве что вместо curios, стоит accessories + curios compat, могу перейти в дискорд если нужно будет больше сведений, может виноват accessories.

![image](https://github.com/MaxBogomol/WizardsReborn/assets/94359925/7ad36457-5148-4610-b560-461449248f7e)

[latest.log](https://github.com/user-attachments/files/15753016/latest.log)

![image](https://github.com/MaxBogomol/WizardsReborn/assets/94359925/1bb54bf3-b59c-48aa-92a2-331d7dbaf19c)

**Comment by MaxBogomol** [comment]
Я вообще впервые узнал что в джеи такое существует. Можете перейти на дс сервер? ссылка есть на странице мода.
