### ISSUE TITLE
Render Item Issues

### ISSUE THREAD

**Issue by Aarods** [MaxBogomol/WizardsReborn#22]
When you have some items with the new light effects in the hot bar, this one starts to glitch. This only happens with certain items.

Mod Incompatibility: Still Testing
Forge: 47.3.5
Version:  0.1.6

![2024-08-14_10 01 34](https://github.com/user-attachments/assets/ddd5bbff-9c82-4b0a-8dda-2fe8253a256e)

**Comment by MaxBogomol** [comment]
ImmidiatelyFast and Lodestone?

**Comment by Aarods** [comment]
Only ImmediatlyFast, and after testing it out, seems that was the problem.
