### ISSUE TITLE
Feature Request: Config option to turn off the worldgen.

### ISSUE THREAD

**Issue by PinkDisorder** [MaxBogomol/WizardsReborn#24]
Hello, thank you for the great mod. As the title suggests, it would be quite helpful for modpack creation to have a config option to disable worldgen in Wizards Reborn.

My use case is quite simple. I wish to build custom ore veins for the mod by making use of gregtech's custom vein generation via kubejs. I can still do this without disabling the worldgen ofc but it'd just be nicer if i could get a matching result.

**Comment by MaxBogomol** [comment]
Worldgen cannot be made config dependent.
The entire worldgen can be changed using datapacks.

**Comment by PinkDisorder** [comment]
How would one go about disabling it via datapacks?

**Comment by PinkDisorder** [comment]
I seem to have figured this out on my own.
```json
{
  "feature": "wizards_reborn:arcanum_ore",
  "placement": [
    {
      "type": "minecraft:count",
      "count": 0
    }
  ]
}
```
