### ISSUE TITLE
[CRASH] Arcane wand in Crystallizer

### ISSUE THREAD

**Issue by SheReyy** [MaxBogomol/WizardsReborn#26]
Forge 47.3.0
Wizard's Reborn: 0.2.2

I placed an Arcane wan in a Wissen Crystallizer? (Sorry I'm currently trying to learn the mod). I was trying to charge the wand.
Edit: Altar* It was the Wissen Altar*

[Here](https://gist.github.com/SheReyy/31935214cf334e2a71b77d6298a5f9a0)'s the crash log.

**Comment by MaxBogomol** [comment]
This is a mistake because I accidentally wrote something wrong when registering the packet.
I can't fix the error right now, because I'm busy.

Please use wissen cell for charging, it shouldn't crash

**Comment by SheReyy** [comment]
> This is a mistake because I accidentally wrote something wrong when registering the packet. I can't fix the error right now, because I'm busy.
> 
> Please use wissen cell for charging, it shouldn't crash

No worries. I'm just trying to learn the mod rn. I'm working on a mod pack and I'm highly interested in using it for the main progression. I absolutely love the concepts, the mechanics and the art style

**Comment by MaxBogomol** [comment]
Thank you for your kind words

**Comment by MaxBogomol** [comment]
Fixed in 0.2.3
