### ISSUE TITLE
Cork Bamboo Salt Lantern crafting recipe have empty(wrong) item. 

### ISSUE THREAD

**Issue by NotShaung** [MaxBogomol/WizardsReborn#29]
**Cork Bamboo Salt Lantern** crafting recipe seems broken.
on latest version **Wizard's Reborn 1.20.1-0.2.3**
![javaw_dcDSyAzVCI](https://github.com/user-attachments/assets/ae3d31cb-1973-4771-96c1-54695b540979)

**Comment by MaxBogomol** [comment]
Already fixed in dev version
