### ISSUE TITLE
Modernfix FasterItemRendering cause incomplete block and item in the Arcanemicon

### ISSUE THREAD

**Issue by ishi-sama** [MaxBogomol/WizardsReborn#3]
**Version:** 
Forge 47.2.5 MC1.20.1

**Mods:** 
curios-forge-5.4.2+1.20.1.jar
modernfix-forge-5.9.3+mc1.20.1 ([FasterItemRendering](https://github.com/embeddedt/ModernFix/wiki/1.20-Summary-of-Patches#mixinperffaster_item_rendering) enable)
wizards_reborn-1.20.1-0.0.6

**Issue:**
Items and blocks' back are not rendered causing them to disappear while rotating.

**Expected:**
Full item and block rendering in the Arcanemicon.

![FasterItemRendering](https://github.com/MaxBogomol/WizardsReborn/assets/41908476/b1a38c95-2298-4f13-83d4-0f2faa299231)
![Rotating](https://github.com/MaxBogomol/WizardsReborn/assets/41908476/6718b808-1c2d-40c8-a546-32d39878613d)

**Comment by MaxBogomol** [comment]
I fixed this bug and slightly changed the lighting of spinning items
