### ISSUE TITLE
Floating items in book cause intense fps lag in big modpacks

### ISSUE THREAD

**Issue by shBLOCK** [MaxBogomol/WizardsReborn#5]
Reading sections of the book that have the floating items brings the fps to a halt in ATM9.

Apparently [instancing `ItemRenderer`s](https://github.com/MaxBogomol/WizardsReborn/blob/c1b40a601b2c9bf0f0317d45b6e0fe120d357585/src/main/java/mod/maxbogomol/wizards_reborn/utils/RenderUtils.java#L209) are really heavy in big packs. So instancing them every frame is probably not a good idea, they should probably be cached or something.

Here's the [spark profile](https://spark.lucko.me/YEEVo1tM2L)

**Comment by MaxBogomol** [comment]
I replaced the customItemRenderer with a static variable, this should help
