### ISSUE TITLE
Render crash when opening client due to Wizards Reborn?

### ISSUE THREAD

**Issue by Arkiln** [MaxBogomol/WizardsReborn#7]
Getting the following crash log when trying to launch client, is this due to a bug with Wizards Reborn?

https://pastebin.com/ZCdQ9HB9

Initial modpack was https://www.curseforge.com/minecraft/modpacks/medieval-mc-mmc4
Let me know if you need any additional information.

Edit: Removing Ars Elemental caused the issue to no longer appear.

**Comment by MaxBogomol** [comment]
this bug is fixed in the latest version of the mod, you can update
